name: Test Secrets Reusable
on:
  workflow_call:
    inputs:
      msg:
        type: string
        default: "hello"
    secrets:
      OPTIONAL:
        required: false
jobs:
  echo:
    runs-on: lux-build-linux-amd64
    steps:
      - run: echo "${{ inputs.msg }}"
