name: Test Build Reusable
on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
      platforms:
        type: string
        default: "linux/amd64"
      runner-amd64:
        type: string
        default: "lux-build-linux-amd64"
    secrets:
      OPTIONAL:
        required: false

jobs:
  build-amd64:
    if: contains(inputs.platforms, 'linux/amd64')
    runs-on: ${{ inputs.runner-amd64 }}
    permissions:
      packages: write
      contents: read
    steps:
      - run: echo "would build ${{ inputs.image }}"
